pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
	dependencyResolutionManagement {
		versionCatalogs {
			devLibs {
				from(files("gradle/dev.versions.toml"))
			}
		}
	}
}

rootProject.name = "cigarette"