name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Set Mod Version
        run: sed -i "s/development_build/${GITHUB_REF##*/}/" gradle.properties 

      - name: Build with Gradle
        run: ./gradlew build

      - name: Rename JAR file
        run: |
          MC_VERSION=$(cat gradle.properties | grep minecraft_version | cut -d '=' -f2)
          JAR_NAME=$(ls build/libs/*.jar | grep -v '\-sources\.jar$')
          NEW_JAR_NAME="cigarette-${GITHUB_REF##*/}+$MC_VERSION.jar"
          mkdir -p dist/release
          mv "$JAR_NAME" "dist/release/$NEW_JAR_NAME"
          echo "Moved JAR to dist/release/$NEW_JAR_NAME"
          echo "NEW_JAR_NAME=$NEW_JAR_NAME" >> $GITHUB_ENV

      - name: Create Release and Upload JAR
        id: create_release
        uses: actions/forgejo-release@v2.7.3
        with:
          direction: upload
          url: https://git.okr765.com
          repo: cigarette/client
          tag: ${{ github.ref }}
          title: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          files: dist/release
