name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Rename JAR file
        run: |
          JAR_NAME=$(ls build/libs/*.jar | grep -v '\-sources\.jar$')  
          NEW_JAR_NAME="cigarette-${GITHUB_REF##*/}.jar"
          mv "$JAR_NAME" "build/libs/$NEW_JAR_NAME"
          echo "Renamed JAR to $NEW_JAR_NAME"
          echo "NEW_JAR_NAME=$NEW_JAR_NAME" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: build/libs/${{ env.NEW_JAR_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
