name: Build dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Set Mod Version
        run: sed -i "s/development_build/${GITHUB_REF##*/}/" gradle.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Rename JAR file
        run: |
          MC_VERSION=$(cat gradle.properties | grep minecraft_version | cut -d '=' -f2)
          JAR_NAME=$(ls build/libs/*.jar | grep -v '\-sources\.jar$')
          NEW_JAR_NAME="cigarette-${GITHUB_REF##*/}+$MC_VERSION.jar"
          mv "$JAR_NAME" "build/libs/$NEW_JAR_NAME"
          echo "Renamed JAR to $NEW_JAR_NAME"
          echo "NEW_JAR_NAME=$NEW_JAR_NAME" >> $GITHUB_ENV

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cigarette-artifact
          path: build/libs/${{ env.NEW_JAR_NAME }}
          retention-days: 30